name: wallet
version: 2.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  get: any
  path: any
  http: any
  cupertino_icons: ^1.0.6
  firebase_auth: any
  cloud_firestore: any
  firebase_database: any
  firebase_messaging: any
  firebase_storage: any
  firebase_core: ^3.0.0
  camera: ^0.11.0
  get_storage: ^2.1.1
  provider: 6.1.2
  google_fonts: 6.2.1
  shared_preferences: any
  timeago: 3.6.1
  quickalert: 1.1.0
  image_picker: ^1.1.2
  fancy_password_field: 2.0.6
  country_picker: ^2.0.26
  get_time_ago: 1.3.1
  logger: ^2.3.0
  fancy_bottom_navigation_plus: 1.0.3
  awesome_dialog: ^3.2.1
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  carousel_slider: ^4.2.1
  overlay_support: 2.1.0
  date_picker_plus: 4.0.0
  share_plus: 9.0.0
  screenshot: 3.0.0
  path_provider: ^2.1.1
  image_gallery_saver: 2.0.3
  dio: 5.4.3+1
  permission_handler: 11.3.1
  url_launcher: ^6.3.0
  url_strategy: 0.2.0
  audioplayers: 6.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/icons/icon.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter: 
  assets: 
    - assets/
    - assets/images/
    - assets/audio/
    - assets/slider/
    - assets/icons/
    - assets/slider/2.jpg
    - assets/audio/SEU4_Ride_08.wav
  uses-material-design: true

