// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjkR8ufdK1QNqXp_zScjbCGc7QIVDvhT0',
    appId: '1:501667206572:web:508b02097a498858ded609',
    messagingSenderId: '501667206572',
    projectId: 'salae-efa45',
    authDomain: 'salae-efa45.firebaseapp.com',
    databaseURL: 'https://salae-efa45-default-rtdb.firebaseio.com',
    storageBucket: 'salae-efa45.appspot.com',
    measurementId: 'G-8K5CGRNQT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM3ow4lh89xZf-5xAf3UdkelcA_SYz2Ms',
    appId: '1:501667206572:android:27ca7d5ed71ccb1fded609',
    messagingSenderId: '501667206572',
    projectId: 'salae-efa45',
    databaseURL: 'https://salae-efa45-default-rtdb.firebaseio.com',
    storageBucket: 'salae-efa45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL1tQqzJ072kCu6Wa7uEb22wIuDMMVgZo',
    appId: '1:501667206572:ios:e855be9c8037f7abded609',
    messagingSenderId: '501667206572',
    projectId: 'salae-efa45',
    databaseURL: 'https://salae-efa45-default-rtdb.firebaseio.com',
    storageBucket: 'salae-efa45.appspot.com',
    iosBundleId: 'paysaw.com.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL1tQqzJ072kCu6Wa7uEb22wIuDMMVgZo',
    appId: '1:501667206572:ios:e855be9c8037f7abded609',
    messagingSenderId: '501667206572',
    projectId: 'salae-efa45',
    databaseURL: 'https://salae-efa45-default-rtdb.firebaseio.com',
    storageBucket: 'salae-efa45.appspot.com',
    iosBundleId: 'paysaw.com.wallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjkR8ufdK1QNqXp_zScjbCGc7QIVDvhT0',
    appId: '1:501667206572:web:508b02097a498858ded609',
    messagingSenderId: '501667206572',
    projectId: 'salae-efa45',
    authDomain: 'salae-efa45.firebaseapp.com',
    databaseURL: 'https://salae-efa45-default-rtdb.firebaseio.com',
    storageBucket: 'salae-efa45.appspot.com',
    measurementId: 'G-8K5CGRNQT2',
  );

}